### ISSUE TITLE
Failed to import module 'python_anticaptcha'

### ISSUE THREAD

**Issue by mathieuzen** [jairoxyz/script.module.cloudscraper#1]
Hi ! First of all, Thanks for sharing the recompiled module for Kodi.

I get this error when it comes to pass the challenge through the recaptcha service.

```
ERROR:root:Unable to load anticaptcha anti reCaptcha provider
Please install/upgrade the python module 'python_anticaptcha' via pip install python-anticaptcha or https://github.com/ad-m/python-anticaptcha/
```

I see it has something to do with the import of a missing python_anticaptcha module but I cannot point where and how I should solve it (not really confident creating kodi addons). I tried to create an addon with the unpacked wheel from `https://pypi.org/project/python-anticaptcha/#files` but without success.

Any idea how to solve it ? Thanks in advance for your help.

**Comment by jairoxyz** [comment]
@mathieuzen thanks for detecting this. I added the python-anticaptcha module. Can you try again? I have no means to test this but can you point me to a url that uses CF and Captcha?

**Comment by jairoxyz** [comment]
Fixed
